### ISSUE TITLE
add handler for node_module

### ISSUE THREAD

**Issue by maxisam** [dhadka/ezcache#27]
First of all, thanks for the great library.

I wonder if we can have a handler for node_module. I know it is kind of against the best practice but we are fine to take it.

basically we just need to use key like hash value of yarn.lock and node version.

To do this in actions/cache@v2, it is like

```yml
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache yarn cache
      uses: actions/cache@v2
      id: cache-yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
```
